### ISSUE TITLE
Colors not displayed correctly.

### ISSUE THREAD

**Issue by kaiser-lord** [University-of-Strathclyde-LTE-Team/moodle-atto_morebackcolors#9] opened 2019-02-18 17:25 UTC
As seen here:
![image](https://user-images.githubusercontent.com/26856174/52967407-c1b5d980-3388-11e9-9b54-cdb3f5953f32.png)
I can't see the colors displayed, I only see collapsed color icons or something like that.

**Comment by kaiser-lord** [comment] 2019-02-19 15:13
I applied this CSS rule:
.editor_atto_menu .open ul.dropdown-menu {
          right:inherit;
}
And it works!, it shows correctly now. I forgot to mention I have the Adaptable theme, and seems to be a problem related to owners of the aforementioned theme. 
Thanks to Derryn Jones, the fourth post here: https://moodle.org/plugins/atto_morefontcolors his solution is what worked for me.

**Comment by ndunand** [comment] 2020-06-25 14:14
Hello, we could not reproduce this on the standard Moodle themes. Therefore I'm closing this for now but feel free to reopen if you think this should be addressed by the plugin.

**Closed as completed by ndunand** 2020-06-25 14:14 UTC
